### ISSUE TITLE
Pul requests for Ergodox layouts

### ISSUE THREAD

**Issue by HughP** [pa7/Keyboard-Heatmap#7]
@Rolzad73 I see that you have [created and added  an ergodox qwerty layout](https://github.com/Rolzad73/Keyboard-Heatmap/commit/51cf47dee670c1631609954bacb9556d02c3e509).

Is there any way to add that to the main repo with a pull request? It looks @pa7 's master has moved a head a bit, but I still think your contribution to the project is valuable. And if everyone agree's it would be nice to add to the master branch.

**Comment by Rolzad73** [comment]
Yes I can definitely do that.

**Comment by pa7** [comment]
thank you guys, I just merged your PR :)
